/* Apollo Freight Solutions Portal - Employee / HR Leave Portal
 * HR/Employee leave UI is isolated from the core ERP runtime.
 */
const HR_API_URL = (window.APOLLO_API_URL || "https://apollo-freighterp-f9kt.onrender.com").replace(/\/$/, "");
const HR_SESSION_KEY = "apollofreighterp-session";
const HR_DECLARATION = "I declare that the information provided in this leave application is true and complete. I understand that weekends and public holidays marked by HR are not deducted from my leave balance, and I will return to work on the stated rejoining date unless an approved extension is granted.";
const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const session = () => { try { return JSON.parse(sessionStorage.getItem(HR_SESSION_KEY) || "null"); } catch { return null; } };
const hrToken = () => String(session()?.token || "");
const hrUser = () => String(session()?.userName || "");
const hrAdmin = () => ["admin", "hr"].includes(String(session()?.role || "").toLowerCase()) && String(session()?.portal || "").toLowerCase() === "employee";
const hrFetch = async (path, options = {}) => {
  const headers = { ...(options.headers || {}), Authorization: `Bearer ${hrToken()}` };
  if (options.body && !headers["Content-Type"]) headers["Content-Type"] = "application/json";
  const response = await fetch(`${HR_API_URL}${path}`, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
};
const today = () => new Date().toISOString().slice(0, 10);
const year = () => new Date().getFullYear();
const fmtDate = v => v ? (() => { const d = new Date(`${String(v).slice(0,10)}T00:00:00Z`); const pad = n => String(n).padStart(2,"0"); return `${pad(d.getUTCDate())}-${pad(d.getUTCMonth()+1)}-${d.getUTCFullYear()}`; })() : "—";
let cache = { config:null, requests:null, summary:null, adminBalances:null, policies:null, leaveTypes:null, delegations:null, ledger:null, calendarBranch:"" };
let balanceFilter = { employee:"", leaveType:"", submitted:false };
let bound = false;
let baseLoadPromise = null;
let adminLoadPromise = null;

const employeeSession = () => String(session()?.portal || "").toLowerCase() === "employee";
const sessionBranch = () => { const raw=String(session()?.branchAccess||"").split(",")[0].trim().toLowerCase(); return /dubai|dxb/.test(raw)?"Dubai":"Kuwait HO"; };
const activeCalendarBranch = () => cache.calendarBranch || sessionBranch();
async function loadConfig(){ cache.config = await hrFetch(`/api/hr/leave-config?year=${year()}&branch=${encodeURIComponent(activeCalendarBranch())}`); return cache.config; }
async function loadRequests(){ cache.requests = (await hrFetch("/api/hr/leave-requests")).rows || []; return cache.requests; }
async function loadAdminBalances(){ cache.adminBalances = (await hrFetch(`/api/hr/admin/balances?year=${year()}`)).rows || []; return cache.adminBalances; }
async function loadPolicies(){ cache.policies = await hrFetch(`/api/hr/admin/policies?year=${year()}`); return cache.policies; }
async function loadLeaveTypes(){ cache.leaveTypes = (await hrFetch("/api/hr/admin/leave-types")).rows || []; return cache.leaveTypes; }
async function loadDelegations(){ cache.delegations = (await hrFetch("/api/hr/admin/delegations")).rows || []; return cache.delegations; }
async function loadLedger(){ cache.ledger = (await hrFetch("/api/hr/leave-ledger")).rows || []; return cache.ledger; }
async function ensureLoaded(){
  if(!employeeSession()) return;
  bindHrEvents();
  if(baseLoadPromise) return baseLoadPromise;
  const work=[]; if(!cache.config) work.push(loadConfig()); if(cache.requests===null) work.push(loadRequests());
  if(!work.length) return Promise.resolve();
  baseLoadPromise=Promise.all(work).catch(e=>console.warn("HR portal data unavailable",e)).finally(()=>{baseLoadPromise=null;requestCoreRender();});
  return baseLoadPromise;
}
async function ensureAdminData(){
  if(!hrAdmin()) return;
  bindHrEvents(); if(adminLoadPromise) return adminLoadPromise;
  // loadRequests() and loadConfig() also have to run here (not just in ensureLoaded()) - Leave
  // Approvals reads cache.requests and HR Calendar & Rules reads cache.config, and an HR/admin
  // user who opens either page directly (without visiting My Leave first, which is what normally
  // triggers ensureLoaded()) would otherwise find that data still null/unfetched, so the page
  // would silently show nothing even though there's real data on the server.
  const work=[]; if(!cache.adminBalances) work.push(loadAdminBalances()); if(!cache.summary) work.push(hrFetch(`/api/hr/admin/summary?year=${year()}`).then(data=>{cache.summary=data;})); if(!cache.policies) work.push(loadPolicies()); if(!cache.leaveTypes) work.push(loadLeaveTypes()); if(cache.requests===null) work.push(loadRequests()); if(!cache.config) work.push(loadConfig());
  if(!work.length) return Promise.resolve();
  adminLoadPromise=Promise.all(work).catch(e=>console.warn("HR admin data unavailable",e)).finally(()=>{adminLoadPromise=null;requestCoreRender();});
  return adminLoadPromise;
}
function requestCoreRender(){ if(typeof window.__APOLLO_HR_RENDER === "function") window.__APOLLO_HR_RENDER(); }
function kpi(title,value,note){ return `<article class="hr-kpi"><strong>${esc(value)}</strong><span>${esc(title)}</span><small>${esc(note)}</small></article>`; }
function panel(title,body,note=""){ return `<article class="panel hr-panel"><div class="hr-panel-head"><div><h3>${esc(title)}</h3>${note?`<small>${esc(note)}</small>`:""}</div></div>${body}</article>`; }
function badge(status){ return `<span class="hr-status hr-status-${esc(String(status||"").toLowerCase().replace(/\s+/g,"-"))}">${esc(status||"")}</span>`; }
function dateDiffText(r){ return `${r.actual_leave_days ?? r.total_days ?? 0} working day(s) • ${r.weekend_days||0} weekend • ${r.public_holiday_days||0} holiday`; }
// Shared by every "this is MY own data" panel (My Leave, Leave Calendar) - cache.requests holds
// the full company-wide list whenever the logged-in user is HR/admin (the backend has to return
// everyone's requests for the Leave Approvals queue to work), so anything showing this person's
// own history has to filter back down to their own rows, or it ends up showing the same
// full-company list that Leave Approvals shows.
function myOwnRequests(){ const myName=hrUser().toLowerCase(); return (cache.requests||[]).filter(r=>String(r.user_name||"").toLowerCase()===myName); }
function renderBalanceCards(balances=[]){
  if(!balances.length) return `<p class="empty-state">No leave balance has been configured for you.</p>`;
  return `<div class="hr-balance-grid">${balances.map(b=>`<article class="hr-balance-card"><strong>${esc(b.leaveTypeName||b.leaveTypeCode)}</strong><div class="hr-balance-number">${esc(b.available)}</div><small>Available</small><dl><div><dt>Entitlement</dt><dd>${esc(b.entitlement)}</dd></div><div><dt>Used</dt><dd>${esc(b.used)}</dd></div><div><dt>Pending</dt><dd>${esc(b.pending)}</dd></div><div><dt>Carry forward</dt><dd>${esc(b.carryForward)}</dd></div></dl><div class="hr-projected">Projected after pending: <strong>${esc(b.projected)}</strong></div></article>`).join("")}</div>`;
}
function renderMyLeave(){
  const cfg=cache.config||{balances:[],leaveTypes:[]}, emp=cfg.employee||{};
  // cache.requests holds every employee's requests when the logged-in user is HR/admin (the
  // backend returns the full list for that role, since Leave Approvals needs to see everyone's
  // requests) - but "My Leave" is this person's own self-service page, so it has to be narrowed
  // back down to just their own requests here, or an HR/admin user would see every employee's
  // leave history duplicated onto their personal "My Applications" list, identical to what shows
  // on the Leave Approvals page.
  const rows=myOwnRequests();
  const pending=rows.filter(r=>r.status==="Pending").reduce((n,r)=>n+Number(r.actual_leave_days||r.total_days||0),0);
  const used=rows.filter(r=>r.status==="Approved").reduce((n,r)=>n+Number(r.actual_leave_days||r.total_days||0),0);
  return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Employee Portal</p><h2>My Leave</h2><p>Complete your leave application and track your balance, approvals and return to work.</p></div><button class="blue-button" data-hr-action="open-leave-form">Apply for Leave</button></div>
  <div class="hr-kpi-grid">${kpi("Available leave",cfg.balances.reduce((n,b)=>n+Number(b.available||0),0),"All leave types")}${kpi("Pending",pending,"Awaiting HR approval")}${kpi("Approved used",used,"Approved requests")}${kpi("Year",year(),"Leave year")}</div>
  ${panel("My Leave Balance",renderBalanceCards(cfg.balances),"Leave is deducted only for working days.")}
  ${panel("My Applications",rows.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Request</th><th>Type</th><th>Period</th><th>Calculation</th><th>Rejoining</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.request_no)}</td><td>${esc(r.leave_type)}</td><td>${fmtDate(r.start_date)} → ${fmtDate(r.end_date)}</td><td>${esc(dateDiffText(r))}</td><td>${fmtDate(r.rejoining_date)}</td><td>${badge(r.status)}</td><td><button class="ghost-button" data-hr-action="view-request" data-id="${esc(r.request_no)}">View</button>${["Pending","Approved","Sent Back"].includes(r.status)?`<button class="ghost-button" data-hr-action="cancel-leave" data-id="${esc(r.request_no)}">Cancel</button>`:""}${r.status==="Approved"&&!r.rejoined_at?`<button class="ghost-button" data-hr-action="rejoin" data-id="${esc(r.request_no)}">I Rejoined</button><button class="ghost-button" data-hr-action="extend-leave" data-id="${esc(r.request_no)}">Request Extension</button>`:""}</td></tr>`).join("")}</tbody></table></div>`:`<p class="empty-state">No leave applications yet.</p>`)}</section>`;
}
function renderBalance(){ if(cache.ledger===null) loadLedger().then(requestCoreRender).catch(()=>{}); const ledger=cache.ledger||[]; const ledgerHtml=ledger.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Date</th><th>Leave Type</th><th>Transaction</th><th>Days</th><th>Balance After</th><th>Reference / Note</th></tr></thead><tbody>${ledger.map(r=>`<tr><td>${fmtDate(r.created_at)}</td><td>${esc(r.leave_type_code)}</td><td>${esc(r.transaction_type)}</td><td>${esc(r.days)}</td><td>${esc(r.balance_after)}</td><td>${esc(r.reference_no||r.reason)}</td></tr>`).join("")}</tbody></table></div>`:`<p class="empty-state">No leave balance transactions yet.</p>`; return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Employee Portal</p><h2>Leave Balance</h2><p>Your entitlement, carry-forward, approved usage, pending requests and projected balance for ${year()}.</p></div><button class="secondary-button" data-hr-action="refresh">Refresh</button></div>${panel(`Leave Balance — ${year()}`,renderBalanceCards(cache.config?.balances||[]),"Available = entitlement + carry-forward + adjustment − approved leave. Pending is shown separately.")}${panel("Leave Ledger",ledgerHtml,"A complete history of approved leave, cancellations and HR adjustments.")}</section>`; }
function calendarGrid(config, rows){
  const now=new Date(), y=now.getUTCFullYear(), m=now.getUTCMonth(), first=new Date(Date.UTC(y,m,1)), last=new Date(Date.UTC(y,m+1,0));
  const holidayMap=new Map((config.holidays||[]).map(h=>[String(h.holiday_date).slice(0,10),h])); const leaveMap=new Map();
  (rows||[]).forEach(r=>{ if(!r.start_date||!r.end_date) return; const s=new Date(`${String(r.start_date).slice(0,10)}T00:00:00Z`), e=new Date(`${String(r.end_date).slice(0,10)}T00:00:00Z`); for(let d=new Date(s);d<=e;d.setUTCDate(d.getUTCDate()+1)) leaveMap.set(d.toISOString().slice(0,10),r.status); });
  const names=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; let cells=names.map(n=>`<div class="hr-cal-head">${n}</div>`).join("");
  for(let i=0;i<first.getUTCDay();i++) cells+=`<div class="hr-cal-cell is-empty"></div>`;
  for(let d=1;d<=last.getUTCDate();d++){ const dt=new Date(Date.UTC(y,m,d)), key=dt.toISOString().slice(0,10), h=holidayMap.get(key), weekend=config.weekends?.includes(dt.getUTCDay()), st=leaveMap.get(key); cells+=`<div class="hr-cal-cell ${weekend?"is-weekend":""} ${h?.day_type==="PUBLIC_HOLIDAY"?"is-holiday":""} ${h?.day_type==="BLACKOUT"?"is-blackout":""} ${st?`is-leave-${String(st).toLowerCase()}`:""}"><strong>${d}</strong>${h?`<small>${esc(h.title)}</small>`:""}${st?`<small>${esc(st)}</small>`:""}</div>`; }
  return `<div class="hr-calendar-grid">${cells}</div>`;
}

async function extendLeave(no){
  const endDate=window.prompt("New leave end date (YYYY-MM-DD):","")||"";
  if(!/^\d{4}-\d{2}-\d{2}$/.test(endDate)) return;
  const reason=window.prompt("Reason for the extension:","")||"";
  if(!reason.trim()) return;
  try{ await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}/extension`,{method:"POST",body:JSON.stringify({endDate,reason})}); cache.requests=null; await loadRequests(); await loadConfig(); requestCoreRender(); window.alert("Extension request submitted for HR approval."); }
  catch(e){ window.alert(e.message); }
}
function renderCalendar(){ const cfg=cache.config||{weekends:[],holidays:[]}; return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Employee Portal</p><h2>Leave Calendar</h2><p>See weekends, public holidays and your leave dates in one calendar.</p></div></div>${panel("Calendar",calendarGrid(cfg,myOwnRequests()))}${panel("Calendar Legend",`<div class="hr-legend"><span>Weekend</span><span>Public Holiday</span><span>My Leave</span><span>Blackout / Restricted</span></div>`)}${panel("Configured Public Holidays & Rules",cfg.holidays?.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Date</th><th>Type</th><th>Title</th><th>Notes</th></tr></thead><tbody>${cfg.holidays.map(h=>`<tr><td>${fmtDate(h.holiday_date)}</td><td>${esc(h.day_type)}</td><td>${esc(h.title)}</td><td>${esc(h.notes)}</td></tr>`).join("")}</tbody></table></div>`:`<p class="empty-state">No special dates configured.</p>`)}</section>`; }
function leaveForm(){
  const cfg=cache.config||{leaveTypes:[]}, emp=cfg.employee||{};
  return `<div class="hr-modal-backdrop" data-hr-modal><div class="hr-modal hr-leave-application"><div class="hr-modal-head"><div><p class="eyebrow">Employee Portal</p><h2>Leave Application</h2><p>Complete all required information before submitting.</p></div><button type="button" class="secondary-button" data-hr-action="close-modal">Close</button></div>
  <form data-hr-form="leave-application" class="hr-form"><section class="hr-form-section"><h3>Employee Information</h3><div class="hr-form-grid"><label>Employee Name<input value="${esc(emp.full_name||hrUser())}" readonly></label><label>Employee Code<input value="${esc(emp.employee_code||"")}" readonly></label><label>Department<input value="${esc(emp.department||"")}" readonly></label><label>Designation<input value="${esc(emp.designation||"")}" readonly></label><label>Reporting Manager<input value="${esc(emp.reporting_manager||"")}" readonly></label></div></section>
  <section class="hr-form-section"><h3>Leave Details</h3><div class="hr-form-grid"><label>Kind of Leave<select name="leaveType" required>${cfg.leaveTypes.map(t=>`<option value="${esc(t.code)}">${esc(t.name)}${t.paid===false?" — Unpaid":""}</option>`).join("")}</select></label><label>Time Period<select name="halfDayType"><option value="">Full Day(s)</option><option value="FIRST_HALF">Half Day — First Half</option><option value="SECOND_HALF">Half Day — Second Half</option></select></label><label>Leave Start Date<input name="startDate" type="date" value="${today()}" required></label><label>Leave End Date<input name="endDate" type="date" value="${today()}" required></label><label>Rejoining Date<input name="rejoiningDate" type="date" required></label><label>Contact Number During Leave<input name="contactDuringLeave" type="tel" required></label><label class="hr-full">Address / Location During Leave<textarea name="leaveAddress" rows="2" required></textarea></label><label>Emergency Contact<input name="emergencyContact" type="tel"></label><label class="hr-full">Reason for Leave<textarea name="reason" rows="3" required placeholder="Please explain the reason for your leave."></textarea></label></div><div class="hr-calculation" data-hr-calculation>Choose dates to calculate actual leave days.</div></section>
  <section class="hr-form-section"><h3>Supporting Document</h3><p class="form-help">Optional unless the selected leave policy requires supporting documentation. PDF/JPG/PNG up to 10 MB.</p><input name="attachment" type="file" accept="application/pdf,.pdf,image/jpeg,image/png"><small data-hr-attachment-status></small></section>
  <section class="hr-form-section"><h3>Employee Self-Declaration</h3><label class="hr-declaration"><input type="checkbox" name="declarationAccepted" value="true" required><span>${esc(HR_DECLARATION)}</span></label></section>
  <p class="hr-form-message" data-hr-message></p><div class="dialog-actions"><button type="button" class="secondary-button" data-hr-action="close-modal">Cancel</button><button type="submit">Submit Leave Application</button></div></form></div></div>`;
}
function renderAdminApprovals(){
  ensureAdminData();
  const rows=cache.requests||[];
  const pending=rows.filter(r=>r.status==="Pending");
  const approved=rows.filter(r=>r.status==="Approved");
  const cancelled=rows.filter(r=>r.status==="Cancelled");
  const rowHtml=r=>`<tr><td>${esc(r.request_no)}</td><td>${esc(r.employee_name)}</td><td>${esc(r.leave_type)}</td><td>${fmtDate(r.start_date)} → ${fmtDate(r.end_date)}</td><td>${esc(dateDiffText(r))}</td><td>${fmtDate(r.rejoining_date)}</td><td>${badge(r.status)}</td><td><button class="ghost-button" data-hr-action="view-request" data-id="${esc(r.request_no)}">${r.status==="Pending"?"Review":"View"}</button>${r.status==="Approved"?`<button class="ghost-button" data-hr-action="cancel-leave" data-id="${esc(r.request_no)}">Cancel</button>`:""}${r.status==="Cancelled"?`<button class="danger-button" data-hr-action="delete-cancelled-leave" data-id="${esc(r.request_no)}">Delete</button>`:""}</td></tr>`;
  const table=(title,items,empty)=>panel(title,items.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Request</th><th>Employee</th><th>Type</th><th>Period</th><th>Actual Leave</th><th>Rejoining</th><th>Status</th><th>Action</th></tr></thead><tbody>${items.map(rowHtml).join("")}</tbody></table></div>`:`<p class="empty-state">${empty}</p>`);
  return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Admin / HR</p><h2>Leave Approvals</h2><p>Review pending applications, see approved leave, and remove cancelled requests. Open any application to see every submitted field and the complete reason.</p></div><button class="secondary-button" data-hr-action="refresh">Refresh</button></div><div class="hr-kpi-grid">${kpi("Pending",pending.length,"Requires HR action")}${kpi("Approved",approved.length,"Approved requests")}${kpi("Cancelled",cancelled.length,"Available for deletion")}${kpi("Employees",cache.summary?.employees?.length||0,"Employee records")}</div>${table("Pending Applications",pending,"No pending leave applications.")}${table("Approved Leave",approved,"No approved leave applications.")}${table("Cancelled Requests",cancelled,"No cancelled requests to delete.")}</section>`;
}
function renderRequestDetails(r){
  const canReview=hrAdmin()&&r.status==="Pending";
  const reasonLabel=r.status==="Rejected"?"Rejection Reason":r.status==="Sent Back"?"Send-Back Comment":"Reviewer Comment";
  const detail=(label,value)=>`<strong>${esc(label)}</strong><span>${esc(value===null||value===undefined||value===""?"—":value)}</span>`;
  return `<div class="hr-detail-modal" data-hr-modal><div class="hr-modal"><div class="hr-modal-head"><h2>${esc(r.request_no)}</h2><button type="button" class="secondary-button" data-hr-action="close-modal">Close</button></div><div class="hr-detail-grid">
    ${detail("Employee",r.employee_name)}${detail("Username",r.user_name)}${detail("Leave Type",r.leave_type)}${detail("Start Date",fmtDate(r.start_date))}${detail("End Date",fmtDate(r.end_date))}${detail("Rejoining Date",fmtDate(r.rejoining_date))}${detail("Total Calendar Days",r.calendar_days)}${detail("Weekend Days",r.weekend_days)}${detail("Public Holiday Days",r.public_holiday_days)}${detail("Actual Leave Days",r.actual_leave_days??r.total_days)}${detail("Late Return Leave Days",r.late_return_days||0)}${detail("Half-Day Type",r.half_day_type)}${detail("Reason / Full Application",r.reason)}${detail("Contact During Leave",r.contact_during_leave)}${detail("Leave Address / Location",r.leave_address)}${detail("Emergency Contact",r.emergency_contact)}${detail("Declaration",r.declaration_accepted?"Accepted":"Not accepted")}${detail("Applied At",r.applied_at)}${detail("Status",r.status)}${detail("Approved By",r.approved_by)}${detail("Approved At",r.approved_at)}${detail("Rejection / Review Comment",r.rejection_reason)}${detail("Cancellation Reason",r.cancellation_reason)}${detail("Created At",r.created_at)}${detail("Updated At",r.updated_at)}${r.attachment_url?`<strong>Supporting Document</strong><span><button class="ghost-button" data-hr-action="view-attachment" data-id="${esc(r.request_no)}">View Document</button></span>`:""}
  </div>${canReview?`<section class="hr-review-form"><h3>Review Decision</h3><label>Comment <small>(required for Reject / Send Back, optional for Approve)</small><textarea data-hr-review-comment rows="2" placeholder="Add a note explaining your decision..."></textarea></label><div class="dialog-actions"><button type="button" class="blue-button" data-hr-action="review-decide" data-decision="approve" data-id="${esc(r.request_no)}">Approve</button><button type="button" class="secondary-button" data-hr-action="review-decide" data-decision="sendback" data-id="${esc(r.request_no)}">Send Back</button><button type="button" class="danger-button" data-hr-action="review-decide" data-decision="reject" data-id="${esc(r.request_no)}">Reject</button></div></section>`:""}</div></div>`;
}
function renderAdminCalendar(){
  ensureAdminData();
  const cfg=cache.config||{weekends:[],holidays:[]};
  const branch=activeCalendarBranch();
  const names=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
  const branchSelector=`<label>Branch<select data-hr-branch-select><option value="Kuwait HO" ${branch==="Kuwait HO"?"selected":""}>Kuwait HO</option><option value="Dubai" ${branch==="Dubai"?"selected":""}>Dubai</option></select></label>`;
  return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Admin / HR</p><h2>HR Calendar & Rules</h2><p>Admin controls weekends, public holidays, blackout dates and working-day overrides - separately for each branch.</p></div><form class="hr-inline-form" onsubmit="return false"><div class="hr-form-grid hr-branch-picker">${branchSelector}</div></form></div>
  ${panel(`Weekend Configuration — ${esc(branch)}`,`<form data-hr-form="weekends" class="hr-inline-form"><input type="hidden" name="branch" value="${esc(branch)}"><div class="hr-weekend-checks">${names.map((n,i)=>`<label><input type="checkbox" name="weekday" value="${i}" ${cfg.weekends.includes(i)?"checked":""}>${esc(n)}</label>`).join("")}</div><button type="submit">Save Weekend Rules for ${esc(branch)}</button></form>`,"Weekends set for one branch only apply to that branch. Anything saved while a branch has no rules of its own falls back to the shared \"All branches\" rule.")}
  ${panel(`Add / Update Calendar Date — ${esc(branch)}`,`<form data-hr-form="holiday" class="hr-form"><input type="hidden" name="branch" value="${esc(branch)}"><div class="hr-form-grid"><label>Date From<input type="date" name="startDate" required></label><label>Date To<input type="date" name="endDate" required></label><label>Type<select name="dayType"><option value="PUBLIC_HOLIDAY">Public Holiday</option><option value="BLACKOUT">Blackout / Restricted</option><option value="WORKING_DAY">Working Day Override</option></select></label><label class="hr-full">Title<input name="title" required></label><label class="hr-full">Notes<textarea name="notes" rows="2"></textarea></label></div><button type="submit">Save Calendar Rule for ${esc(branch)}</button></form>`)}
  ${panel(`Configured Dates — ${esc(branch)}`,cfg.holidays?.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Date</th><th>Branch</th><th>Type</th><th>Title</th><th>Notes</th><th>Action</th></tr></thead><tbody>${cfg.holidays.map(h=>`<tr><td>${fmtDate(h.holiday_date)}</td><td>${esc(h.branch)}</td><td>${esc(h.day_type)}</td><td>${esc(h.title)}</td><td>${esc(h.notes)}</td><td><button class="ghost-button" data-hr-action="delete-calendar" data-id="${esc(h.id)}">Remove</button></td></tr>`).join("")}</tbody></table></div>`:`<p class="empty-state">No configured dates for ${esc(branch)} (or shared "All branches" dates).</p>`,`Dates saved as "All" apply to every branch; dates saved for ${esc(branch)} specifically only apply here.`)}
  </section>`;
}
function renderAdminBalance(){
  ensureAdminData();
  const people=cache.summary?.employees||[], types=cache.leaveTypes||[], selectedEmployee=balanceFilter.employee, selectedType=balanceFilter.leaveType;
  const employeeOptions=people.map(e=>`<option value="${esc(e.user_name)}" ${selectedEmployee===e.user_name?"selected":""}>${esc(e.full_name||e.user_name)} — ${esc(e.employee_code||"")}</option>`).join("");
  const selectedRow=(cache.adminBalances||[]).find(e=>String(e.user_name).toLowerCase()===String(selectedEmployee).toLowerCase());
  const typeOptions=(selectedRow?.balances||[]).map(b=>`<option value="${esc(b.leaveTypeCode)}" ${selectedType===b.leaveTypeCode?"selected":""}>${esc(b.leaveTypeName)}</option>`).join("");
  const selectedBalance=selectedRow?.balances?.find(b=>String(b.leaveTypeCode).toUpperCase()===String(selectedType).toUpperCase());
  const result=balanceFilter.submitted&&selectedRow&&selectedBalance?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Employee</th><th>Department</th><th>Leave Type</th><th>Entitlement</th><th>Carry Forward</th><th>Adjustment</th><th>Previous Used</th><th>Used</th><th>Pending</th><th>Available</th><th>Projected</th></tr></thead><tbody><tr><td>${esc(selectedRow.full_name||selectedRow.user_name)}</td><td>${esc(selectedRow.department||"")}</td><td>${esc(selectedBalance.leaveTypeName)}</td><td>${esc(selectedBalance.entitlement)}</td><td>${esc(selectedBalance.carryForward)}</td><td>${esc(selectedBalance.adjustment)}</td><td>${esc(selectedBalance.previousUsed||0)}</td><td>${esc(selectedBalance.used)}</td><td>${esc(selectedBalance.pending)}</td><td><strong>${esc(selectedBalance.available)}</strong></td><td>${esc(selectedBalance.projected)}</td></tr></tbody></table></div>`:`<p class="empty-state">Select one employee and one leave type, then press Search to view the balance.</p>`;
  return `<section class="hr-page"><div class="hr-hero"><div><p class="eyebrow">Admin / HR</p><h2>HR Leave Balances</h2><p>Filter by one employee first, then view one leave type balance.</p></div></div>${panel("Balance Rule",`<div class="hr-rule-box"><strong>Available = Entitlement + Carry Forward + Adjustment − Approved Leave</strong><br>Weekends count as leave days. Public holidays do not consume leave.</div>`)}${panel("Find Employee Leave Balance",`<form data-hr-form="balance-filter" class="hr-form"><div class="hr-form-grid"><label>Employee<select name="employee" required><option value="">Select employee</option>${employeeOptions}</select></label><label>Leave Type<select name="leaveType" ${selectedRow?"":"disabled"} required><option value="">${selectedRow?"Select leave type":"Select an employee first"}</option>${typeOptions}</select></label></div><button type="submit" class="blue-button">Search</button></form>`)}${panel(`Selected Balance — ${year()}`,result)}</section>`;
}
function renderDelegations(){ if(cache.delegations===null) loadDelegations().then(requestCoreRender).catch(()=>{}); const people=cache.summary?.employees||[], rows=cache.delegations||[]; const options=people.map(e=>`<option value="${esc(e.user_name)}">${esc(e.full_name||e.user_name)}</option>`).join(""); return panel("Delegated Leave Approval",`<form data-hr-form="delegation" class="hr-form"><div class="hr-form-grid"><label>Delegator<select name="delegatorUserName" required>${options}</select></label><label>Delegate<select name="delegateUserName" required>${options}</select></label><label>Start<input type="date" name="startDate" value="${today()}" required></label><label>End<input type="date" name="endDate" required></label><label class="hr-full">Notes<textarea name="notes" rows="2"></textarea></label></div><button type="submit">Save Delegation</button></form>${rows.length?`<div class="hr-table-wrap"><table class="hr-table"><thead><tr><th>Delegator</th><th>Delegate</th><th>Period</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.delegator_user_name)}</td><td>${esc(r.delegate_user_name)}</td><td>${fmtDate(r.start_date)} → ${fmtDate(r.end_date)}</td><td>${r.active?"Active":"Ended"}</td><td>${r.active?`<button class="ghost-button" data-hr-action="remove-delegation" data-id="${esc(r.id)}">End</button>`:""}</td></tr>`).join("")}</tbody></table></div>`:""}`,"A delegate can approve or reject requests only during the selected dates."); }
function renderRequestUploadStatus(){ return ""; }
function readFileBase64(file){ return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(new Error("The selected file could not be read."));r.readAsDataURL(file);}); }
async function submitLeave(form){
  const data=Object.fromEntries(new FormData(form).entries()); data.declarationAccepted=form.querySelector("[name=declarationAccepted]")?.checked===true;
  const file=form.querySelector("[name=attachment]")?.files?.[0]; const msg=form.querySelector("[data-hr-message]");
  const selectedType=(cache.config?.leaveTypes||[]).find(t=>String(t.code)===String(data.leaveType));
  try{
    if(selectedType?.require_attachment && file==null){ const start=data.startDate,end=data.endDate; const calc=await hrFetch(`/api/hr/calendar?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}`); const s=new Date(`${start}T00:00:00Z`),e=new Date(`${end}T00:00:00Z`); let working=0; const hs=new Map((calc.holidays||[]).map(h=>[String(h.holiday_date).slice(0,10),h])); for(let d=new Date(s);d<=e;d.setUTCDate(d.getUTCDate()+1)){const k=d.toISOString().slice(0,10);if(hs.get(k)?.day_type!=="PUBLIC_HOLIDAY")working++;} if(working>=Number(selectedType.attachment_after_days||0)) throw new Error(`${selectedType.name} requires a supporting document for this leave period.`); }
    const result=await hrFetch("/api/hr/leave-requests",{method:"POST",body:JSON.stringify(data)});
    if(file){ if(file.size>10*1024*1024) throw new Error("Supporting document must be 10 MB or smaller."); const base64=await readFileBase64(file); await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(result.row.request_no)}/attachment`,{method:"POST",body:JSON.stringify({fileName:file.name,mimeType:file.type,contentBase64:base64})}); }
    if(msg) msg.textContent=`Submitted ${result.row.request_no}. Actual leave days: ${result.calculation.actualLeaveDays}.`;
    await loadConfig(); await loadRequests(); setTimeout(()=>document.querySelector("[data-hr-modal]")?.remove(),700); requestCoreRender();
  }catch(e){if(msg) msg.textContent=e.message;}
}
async function decide(no,decision,reasonOverride){
  let reason=reasonOverride;
  if(reason===undefined){
    if(decision==="reject"){reason=window.prompt("Enter rejection reason:","")||"";if(!reason.trim())return false;}
    else if(decision==="sendback"){reason=window.prompt("Enter a comment for sending this back:","")||"";if(!reason.trim())return false;}
    else reason="";
  } else if((decision==="reject"||decision==="sendback")&&!String(reason).trim()){
    window.alert(`A comment is required to ${decision==="reject"?"reject":"send back"} this request.`);
    return false;
  }
  try{
    await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}/decision`,{method:"PUT",body:JSON.stringify({decision,reason})});
    await loadRequests();await loadAdminBalances();
    window.__APOLLO_AUDIT__?.(decision==="approve"?"Approved leave request":decision==="reject"?"Rejected leave request":"Sent back leave request",no,reason||"");
    requestCoreRender();
    return true;
  }catch(e){window.alert(e.message);return false;}
}
async function cancel(no){const reason=window.prompt("Cancellation reason:","Cancelled by employee")||"";try{await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}/cancel`,{method:"POST",body:JSON.stringify({reason})});await loadRequests();await loadConfig();window.__APOLLO_AUDIT__?.("Cancelled leave request",no,reason);requestCoreRender();}catch(e){window.alert(e.message);}}
async function rejoin(no,actualReturnDate){try{const r=await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}/rejoin`,{method:"POST",body:JSON.stringify({actualReturnDate})});await loadRequests();requestCoreRender();window.alert(r.lateReturnDays?`Rejoin saved. ${r.lateReturnDays} late leave day(s) were deducted.`:"Rejoin saved successfully.");}catch(e){window.alert(e.message);}}
function rejoinForm(r){return `<div class="hr-modal-backdrop" data-hr-modal><div class="hr-modal"><div class="hr-modal-head"><h2>Rejoin Work — ${esc(r.request_no)}</h2><button type="button" class="secondary-button" data-hr-action="close-modal">Close</button></div><form data-hr-form="rejoin" data-id="${esc(r.request_no)}" class="hr-form"><p class="form-help">Promised return date: <strong>${fmtDate(r.rejoining_date)}</strong>. If you return later, the extra paid-leave days will be deducted and the balance may become negative.</p><label>Actual Return Date<input type="date" name="actualReturnDate" min="${esc(r.rejoining_date||"")}" required></label><button type="submit" class="blue-button">Submit Rejoin</button></form></div></div>`;}
async function viewAttachment(no){try{const r=await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}/attachment`);window.open(r.url,"_blank","noopener");}catch(e){window.alert(e.message);}}
async function saveHoliday(form){try{const data=Object.fromEntries(new FormData(form).entries());await hrFetch("/api/hr/calendar/holiday",{method:"POST",body:JSON.stringify(data)});await loadConfig();form.reset();window.__APOLLO_AUDIT__?.("Saved public holiday / calendar date",`${data.holidayDate} — ${data.title}`,`${data.dayType} (${data.branch})`);requestCoreRender();}catch(e){window.alert(e.message);}}
async function saveWeekends(form){try{const weekdays=Array.from(form.querySelectorAll("[name=weekday]:checked")).map(x=>Number(x.value));const branch=form.querySelector("[name=branch]")?.value||activeCalendarBranch();await hrFetch("/api/hr/calendar/weekends",{method:"POST",body:JSON.stringify({weekdays,branch})});await loadConfig();window.__APOLLO_AUDIT__?.("Updated weekend rules",branch,`Weekdays: ${weekdays.join(", ")}`);requestCoreRender();}catch(e){window.alert(e.message);}}
async function deleteCalendar(id){if(!window.confirm("Remove this calendar rule?"))return;try{await hrFetch(`/api/hr/calendar/holiday/${encodeURIComponent(id)}`,{method:"DELETE"});await loadConfig();window.__APOLLO_AUDIT__?.("Deleted public holiday / calendar date",String(id),"");requestCoreRender();}catch(e){window.alert(e.message);}}
async function savePolicy(form){try{const data=Object.fromEntries(new FormData(form).entries());await hrFetch("/api/hr/admin/policies",{method:"PUT",body:JSON.stringify(data)});cache.policies=null;cache.adminBalances=null;await ensureAdminData();window.__APOLLO_AUDIT__?.("Updated employee leave policy / balance",`${data.userName} — ${data.leaveTypeCode}`,`Entitlement ${data.entitlement}, Carry ${data.carryForward}, Adjustment ${data.adjustment}`);requestCoreRender();form.reset();}catch(e){window.alert(e.message);}}
async function deleteCancelledLeave(no){
  if(!hrAdmin()||!window.confirm(`Delete cancelled request ${no}? This cannot be undone.`))return;
  try{await hrFetch(`/api/hr/leave-requests/${encodeURIComponent(no)}`,{method:"DELETE"});cache.requests=null;await loadRequests();window.__APOLLO_AUDIT__?.("Deleted cancelled leave request",no,"");requestCoreRender();}catch(e){window.alert(e.message);}
}
function policyEditForm(p){return `<div class="hr-modal-backdrop" data-hr-modal><div class="hr-modal"><div class="hr-modal-head"><h2>Edit Employee Leave Policy</h2><button type="button" class="secondary-button" data-hr-action="close-modal">Close</button></div><form data-hr-form="policy" class="hr-form"><div class="hr-form-grid"><label>Employee<input name="userName" value="${esc(p.user_name)}" readonly></label><label>Leave Type<input name="leaveTypeCode" value="${esc(p.leave_type_code)}" readonly></label><label>Year<input name="year" type="number" value="${esc(p.year||year())}" required></label><label>Adjustment Start Date<input name="adjustmentStartDate" type="date" value="${esc(p.adjustment_start_date||"")}"></label><label>Adjustment End Date<input name="adjustmentEndDate" type="date" value="${esc(p.adjustment_end_date||"")}"></label><label class="hr-full"><span data-hr-policy-calculation>Saved date range: ${esc(p.adjustment_start_date||"not set")} to ${esc(p.adjustment_end_date||"not set")}. Changing the range recalculates working days excluding weekends and public holidays.</span></label><label>Branch<input name="branch" value="Kuwait HO" readonly></label><label>Entitlement<input name="entitlement" type="number" min="0" step="0.5" value="${esc(p.entitlement)}" required></label><label>Carry Forward<input name="carryForward" type="number" min="0" step="0.5" value="${esc(p.carry_forward||0)}"></label><label>Adjustment<input name="adjustment" type="number" step="0.5" value="${esc(p.adjustment||0)}"></label><label>Previous Used Leave<input name="previousUsedDays" type="number" min="0" step="0.5" value="${esc(p.previous_used_days||0)}"></label><label class="hr-full">Notes<textarea name="notes" rows="2">${esc(p.notes||"")}</textarea></label></div><button type="submit">Save Policy</button></form></div></div>`;}
async function deletePolicy(id){if(!hrAdmin()||!window.confirm("Delete this employee-specific leave policy?"))return;try{await hrFetch(`/api/hr/admin/policies/${encodeURIComponent(id)}`,{method:"DELETE"});cache.policies=null;cache.adminBalances=null;await loadPolicies();window.__APOLLO_AUDIT__?.("Deleted employee leave policy",String(id),"");requestCoreRender();}catch(e){window.alert(e.message);}}
function leaveTypeEditForm(t){return `<div class="hr-modal-backdrop" data-hr-modal><div class="hr-modal"><div class="hr-modal-head"><h2>Edit Leave Type</h2><button type="button" class="secondary-button" data-hr-action="close-modal">Close</button></div><form data-hr-form="leave-type" class="hr-form"><div class="hr-form-grid"><label>Code<input name="code" value="${esc(t.code)}" readonly></label><label>Name<input name="name" value="${esc(t.name)}" required></label><label>Annual Entitlement<input name="annualEntitlement" type="number" min="0" step="0.5" value="${esc(t.annual_entitlement)}"></label><label>Paid<select name="paid"><option value="true" ${t.paid?"selected":""}>Paid</option><option value="false" ${!t.paid?"selected":""}>Unpaid</option></select></label><label>Half Day<select name="allowHalfDay"><option value="true" ${t.allow_half_day?"selected":""}>Allowed</option><option value="false" ${!t.allow_half_day?"selected":""}>Not Allowed</option></select></label><label>Hourly<select name="allowHourly"><option value="true" ${t.allow_hourly?"selected":""}>Allowed</option><option value="false" ${!t.allow_hourly?"selected":""}>Not Allowed</option></select></label><label>Require Attachment<select name="requireAttachment"><option value="true" ${t.require_attachment?"selected":""}>Yes</option><option value="false" ${!t.require_attachment?"selected":""}>No</option></select></label><label>Attachment After Days<input name="attachmentAfterDays" type="number" min="0" step="0.5" value="${esc(t.attachment_after_days||0)}"></label><label>During Probation<select name="allowDuringProbation"><option value="true" ${t.allow_during_probation?"selected":""}>Allowed</option><option value="false" ${!t.allow_during_probation?"selected":""}>Restricted</option></select></label><label>Carry Forward<select name="allowCarryForward"><option value="true" ${t.allow_carry_forward?"selected":""}>Yes</option><option value="false" ${!t.allow_carry_forward?"selected":""}>No</option></select></label><label>Maximum Carry Forward<input name="maxCarryForward" type="number" min="0" step="0.5" value="${esc(t.max_carry_forward||0)}"></label><label>Allow Negative Balance<select name="allowNegativeBalance"><option value="true" ${t.allow_negative_balance?"selected":""}>Yes</option><option value="false" ${!t.allow_negative_balance?"selected":""}>No</option></select></label><label>Allow Encashment<select name="allowEncashment"><option value="true" ${t.allow_encashment?"selected":""}>Yes</option><option value="false" ${!t.allow_encashment?"selected":""}>No</option></select></label><label>Active<select name="active"><option value="true" ${t.active!==false?"selected":""}>Active</option><option value="false" ${t.active===false?"selected":""}>Inactive</option></select></label></div><button type="submit">Save Leave Type</button></form></div></div>`;}
async function deleteLeaveType(code){if(!hrAdmin()||!window.confirm(`Deactivate leave type ${code}?`))return;try{await hrFetch(`/api/hr/admin/leave-types/${encodeURIComponent(code)}`,{method:"DELETE"});cache.config=null;cache.policies=null;cache.leaveTypes=null;await loadConfig();await loadPolicies();await loadLeaveTypes();window.__APOLLO_AUDIT__?.("Deactivated leave type",code,"");requestCoreRender();}catch(e){window.alert(e.message);}}
async function saveLeaveType(form){try{const data=Object.fromEntries(new FormData(form).entries());await hrFetch("/api/hr/admin/leave-types",{method:"PUT",body:JSON.stringify(data)});cache.config=null;cache.policies=null;cache.leaveTypes=null;await loadConfig();await loadPolicies();await loadLeaveTypes();window.__APOLLO_AUDIT__?.("Updated company-wide leave type",data.code,data.name);requestCoreRender();form.reset();}catch(e){window.alert(e.message);}}
function openModal(html){document.querySelector("[data-hr-modal]")?.remove();document.body.insertAdjacentHTML("beforeend",html);bindHrEvents();}
function bindHrEvents(){if(bound)return;bound=true;
  document.addEventListener("click",async e=>{const b=e.target.closest("[data-hr-action]");if(!b)return;const a=b.dataset.hrAction,id=b.dataset.id;if(a==="open-leave-form")openModal(leaveForm());else if(a==="close-modal")b.closest("[data-hr-modal]")?.remove();else if(a==="review-decide"){const modal=b.closest("[data-hr-modal]");const comment=modal?.querySelector("[data-hr-review-comment]")?.value||"";const ok=await decide(id,b.dataset.decision,comment);if(ok)modal?.remove();}else if(a==="cancel-leave")await cancel(id);else if(a==="rejoin"){const r=(cache.requests||[]).find(x=>x.request_no===id);if(r)openModal(rejoinForm(r));}else if(a==="rejoin")await rejoin(id);else if(a==="view-request"){const r=(cache.requests||[]).find(x=>x.request_no===id);if(r)openModal(renderRequestDetails(r));}else if(a==="view-attachment")await viewAttachment(id);else if(a==="delete-cancelled-leave")await deleteCancelledLeave(id);else if(a==="edit-policy"){const p=(cache.policies?.policies||[]).find(x=>String(x.id)===String(id));if(p)openModal(policyEditForm(p));}else if(a==="delete-policy")await deletePolicy(id);else if(a==="edit-leave-type"){const t=(cache.policies?.types||[]).find(x=>String(x.code)===String(id));if(t)openModal(leaveTypeEditForm(t));}else if(a==="delete-leave-type")await deleteLeaveType(id);else if(a==="delete-calendar")await deleteCalendar(id);else if(a==="refresh"){cache.config=null;cache.requests=null;cache.adminBalances=null;cache.policies=null;cache.leaveTypes=null;cache.ledger=null;await ensureLoaded();if(hrAdmin())await ensureAdminData();}});
  document.addEventListener("submit",async e=>{const f=e.target.closest("form[data-hr-form]");if(!f)return;e.preventDefault();if(f.dataset.hrForm==="leave-application")await submitLeave(f);else if(f.dataset.hrForm==="rejoin"){await rejoin(f.dataset.id,f.querySelector("[name=actualReturnDate]").value);f.closest("[data-hr-modal]")?.remove();}else if(f.dataset.hrForm==="holiday")await saveHoliday(f);else if(f.dataset.hrForm==="weekends")await saveWeekends(f);else if(f.dataset.hrForm==="policy")await savePolicy(f);else if(f.dataset.hrForm==="leave-type")await saveLeaveType(f);});
  document.addEventListener("change",async e=>{const balanceForm=e.target.closest("form[data-hr-form=balance-filter]");if(balanceForm&&e.target.name==="employee"){balanceFilter={employee:String(e.target.value||""),leaveType:"",submitted:false};requestCoreRender();return;}const f=e.target.closest("form[data-hr-form=leave-application]");if(f&&["startDate","endDate","halfDayType"].includes(e.target.name)){await updateCalculation(f);return;}const p=e.target.closest("form[data-hr-form=policy]");if(p&&["adjustmentStartDate","adjustmentEndDate","userName"].includes(e.target.name))await updatePolicyRange(p);});
}
async function updatePolicyRange(form){const start=form.querySelector("[name=adjustmentStartDate]")?.value,end=form.querySelector("[name=adjustmentEndDate]")?.value,calc=form.querySelector("[data-hr-policy-calculation]"),employee=form.querySelector("[name=userName]")?.selectedOptions?.[0],branch=employee?.dataset.branch||"Kuwait HO",adjustment=form.querySelector("[name=adjustment]");form.querySelector("[name=branch]").value=branch;if(!start||!end){calc.textContent="Choose an adjustment date range to calculate working leave days. Public holidays are excluded; weekends count as leave days.";return;}if(end<start){calc.textContent="Adjustment end date must be on or after the start date.";return;}try{const r=await hrFetch(`/api/hr/calendar?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}&branch=${encodeURIComponent(branch)}`);const s=new Date(`${start}T00:00:00Z`),e=new Date(`${end}T00:00:00Z`);const hs=new Map((r.holidays||[]).map(h=>[String(h.holiday_date).slice(0,10),h]));let weekend=0,holiday=0,working=0;for(let d=new Date(s);d<=e;d.setUTCDate(d.getUTCDate()+1)){const k=d.toISOString().slice(0,10);if(hs.has(k)&&hs.get(k).day_type==="PUBLIC_HOLIDAY")holiday++;else{if((r.weekends||[]).includes(d.getUTCDay()))weekend++;working++;}}adjustment.value=working;calc.innerHTML=`<strong>Calculated adjustment: ${working} working day(s)</strong> • Weekend: ${weekend} • Public holiday/restricted: ${holiday} • Branch: ${esc(branch)}`;}catch(e){calc.textContent=e.message;}}
async function updateCalculation(form){const start=form.querySelector("[name=startDate]")?.value,end=form.querySelector("[name=endDate]")?.value,half=form.querySelector("[name=halfDayType]")?.value,calc=form.querySelector("[data-hr-calculation]");if(!start||!end){calc.textContent="Choose dates to calculate actual leave days.";return;}try{const r=await hrFetch(`/api/hr/calendar?from=${encodeURIComponent(start)}&to=${encodeURIComponent(end)}`);const s=new Date(`${start}T00:00:00Z`),e=new Date(`${end}T00:00:00Z`);let weekend=0,holiday=0,working=0;const hs=new Map((r.holidays||[]).map(h=>[String(h.holiday_date).slice(0,10),h]));for(let d=new Date(s);d<=e;d.setUTCDate(d.getUTCDate()+1)){const k=d.toISOString().slice(0,10);if(hs.has(k)&&hs.get(k).day_type==="PUBLIC_HOLIDAY")holiday++;else{if(r.weekends.includes(d.getUTCDay())){weekend++;}working++;}}if(["FIRST_HALF","SECOND_HALF"].includes(half)){if(start!==end){calc.innerHTML=`<strong>Half-day leave must use the same start and end date.</strong>`;return;}working=Math.max(0,working-.5);}let rejoin=new Date(e);do{rejoin.setUTCDate(rejoin.getUTCDate()+1);}while(hs.has(rejoin.toISOString().slice(0,10))&&hs.get(rejoin.toISOString().slice(0,10)).day_type==="PUBLIC_HOLIDAY");const rejoinField=form.querySelector("[name=rejoiningDate]");if(rejoinField&&!rejoinField.value)rejoinField.value=rejoin.toISOString().slice(0,10);calc.innerHTML=`<strong>Actual leave days: ${working}</strong> • Calendar: ${Math.round((e-s)/86400000)+1} • Weekend: ${weekend} • Public holiday/restricted: ${holiday} • Suggested rejoining: ${rejoin.toISOString().slice(0,10)}`;}catch(e){calc.textContent=e.message;}}
window.ApolloHR={renderMyLeave:()=>{ensureLoaded();return renderMyLeave();},renderBalance:()=>{ensureLoaded();return renderBalance();},renderCalendar:()=>{ensureLoaded();return renderCalendar();},renderAdminApprovals:()=>{ensureAdminData();return renderAdminApprovals();},renderAdminCalendar:()=>{ensureAdminData();return renderAdminCalendar();},renderAdminPolicies:()=>{ensureAdminData();return renderAdminPolicies()+renderDelegations();},renderAdminBalance:()=>{ensureAdminData();return renderAdminBalance();}};
window.addEventListener("apollo-hr-refresh",requestCoreRender);
document.addEventListener("change",async event=>{const select=event.target.closest("[data-hr-branch-select]");if(!select)return;cache.calendarBranch=select.value;await loadConfig();requestCoreRender();});
document.addEventListener("click",async event=>{const button=event.target.closest("[data-hr-action='extend-leave'],[data-hr-action='remove-delegation']");if(!button)return;if(button.dataset.hrAction==="extend-leave")return extendLeave(button.dataset.id);if(!window.confirm("End this delegated approval?"))return;try{await hrFetch(`/api/hr/admin/delegations/${encodeURIComponent(button.dataset.id)}`,{method:"DELETE"});cache.delegations=null;await loadDelegations();requestCoreRender();}catch(e){window.alert(e.message);}});
document.addEventListener("submit",async event=>{const form=event.target.closest("form[data-hr-form='balance-filter']");if(!form)return;event.preventDefault();const data=Object.fromEntries(new FormData(form).entries());balanceFilter={employee:String(data.employee||""),leaveType:String(data.leaveType||""),submitted:true};requestCoreRender();});
  document.addEventListener("submit",async event=>{const form=event.target.closest("form[data-hr-form='delegation']");if(!form)return;event.preventDefault();try{await hrFetch("/api/hr/admin/delegations",{method:"PUT",body:JSON.stringify(Object.fromEntries(new FormData(form).entries()))});cache.delegations=null;await loadDelegations();form.reset();requestCoreRender();}catch(e){window.alert(e.message);}});
bindHrEvents();
ensureLoaded();
setTimeout(requestCoreRender,0);
